#%RAML 1.0 Trait
  headers:
    client_id:
      type: string
      example: c10da38c14724a398f3172c1bafb0387
    client_secret:
      type: string
      example: c10da38c14724a398f3172c1bafb0387
  responses:
    401:
      description: Unauthorized or invalid client application credentials
    500:
      description: Bad response from authorization server, or WSDL SOAP Fault error