#%RAML 1.0 NamedExample
value:
  "accountId": "ID12345678"
  "accountSirenSiret": "41021801000032"
  "accountSic": "90389785"
  "accountName": "CEGID"
  "billingStreet": " 52 Quai Paul Sedallian"
  "billingPostalCode": "69009"
  "billingCity": "Lyon"
  "billingCountry": "FRANCE"
  "accountPhone": "0811884888"
  "industryCode": "5829C"