#%RAML 1.0 NamedExample
value:
  - itemId: "01t9E000007gBQ4QAM"
    referenceNumber: "A0000151"
    itemName: "Article avec Royalties"
    itemFamily: "Hardware and Other"
    structureLevel2: "Other"
    category: "602"
    noRoyalty: "true"
    percentageOfTurnover: "false"
    quantityDeclarative: "false"
    countermark: "false"
    optionalSKU: "01t9E000007gBQ4QAM"
    metric: "60"
    defaultQuantity: "1.0"
    configuredSKU: "01t9E000007OnDSQA0"
    productLine: ""
    euCustomCode: ""
    coreBusiness: ""
    netWeight: ""
    buyingMetric: "432"
  - itemId: "01t9E000007gBQ4QAM"
    referenceNumber: "A0000155"
    itemName: "Article de secours"
    itemFamily: "Hardware and Other"
    structureLevel2: "Other"
    category: "602"
    noRoyalty: "true"
    percentageOfTurnover: "false"
    quantityDeclarative: "false"
    countermark: "false"
    optionalSKU: "01t9E000007gh9cQAA"
    metric: "60"
    defaultQuantity: "1.0"
    configuredSKU: "01t9E000007OnDSQA0"
    productLine: ""
    euCustomCode: ""
    coreBusiness: ""
    netWeight: ""
    buyingMetric: "432"
