#%RAML 1.0 NamedExample
value: 
  orderNumber: "00000107"
  accountId: "0011w00000W2veFAAR"
  accountName: ""
  billingStreet: "113 Rue Anatole France\nBatiment C"
  billingPostalCode: "92300"
  billingCity: "Levallois-Perret"
  billingCountry: "France"
  accountPhone: ""
  accountSirenSiret: ""
  contactBuyingPersona: "Managing Director"
  contactSalutation: "Mr."
  contactLastName: "MK"
  contactFirstName: "Mister"
  contactEmail: "mk@devoteam.test"
  contactPhone: "010606060606"
  salesRepresentativeEmployeeNumber: ""
  salesRepresentativeLastName: "Hug"
  salesRepresentativeFirstName: "Bertrand"
  salesRepresentativePhone: ""
  salesRepresentativeEmail: ""
  accountSic: ""
  quotePriceBookCurrency: "EUR"
  quotePriceBookDefaultICS: "FR14ZZZ497659"
  quotePriceBookZuoraEntity: "056"
  umr: "00RC0000567000325400002B00"
  billToContactId: ""
  
  