#%RAML 1.0 NamedExample
value: 
  -   discountSchedule: "01s1t0000048XiVAAU"
      id: "abet234et468"
      lowerBound: 3.0
      maxUpperBound: 1.0
      upperBound: 1.0
      maximumPrice: 2000
      name: "LvlSP-000000077"
      serviceLevel: "3. Private"
      priceBookId: "01s1t0000048XiVAAU"
      currency: "EUR"
      productId: "01t9E000007PEmtQAG"
      productType: "Block_Pricing"
      regularPrice: 1000

  -   discountSchedule: "01s1t0000048XiVAAU"
      id: "abet234et468"
      lowerBound: 3.0
      maxUpperBound: 1.0
      upperBound: 1.0
      maximumPrice: 2000
      name: "LvlSP-000000077"
      serviceLevel: "3. Private"
      priceBookId: "01s1t0000048XiVAAU"
      currency: "EUR"
      productId: "01t9E000007PEmtQAG"
      productType: "Block_Pricing"
      regularPrice: 1000

  
  
  