#%RAML 1.0 NamedExample
value: 
  - name : "lvlsp-000000135"
    serviceLevelPrice: "1. connect"
    product: 
      attributes : 
        type: "product2"
        url : "/services/data/v47.0/sobjects/product2/01t1t000001HUkgAAG"
      referenceNumber : "k0000081"
      solutionRange: 4047
      commercialLaunch : "2019-07-12"
      endOfCommercialization : "2019-08-02"
      name : "cegid hr ultimate start"
      pricingModel : "flat rate + overage"
  - name : "lvlsp-000000135"
    serviceLevelPrice: "1. connect"
    product : 
      attributes : 
        type: "product2"
        url : "/services/data/v47.0/sobjects/product2/01t1t000001HUkgAAG"
      referenceNumber : "k0000081"
      solutionRange: 4047
      commercialLaunch : "2019-07-12"
      endOfCommercialization : "2019-07-22"
      name : "cegid hr ultimate start"
      pricingModel : "flat rate + overage"
  
  
  