#%RAML 1.0 NamedExample
value: 
    createById: "0051t000003bFzVAAU"
    createDate: "2020-01-13T15:20:49.000Z"
    currencyIsoCode: "EUR"
    id: "a0G9E0000098CuQUAU"
    isDeleted: false
    lastModifiedById: "0051t000003bFzVAAU"
    lastModifiedDate: "2020-01-14T10:26:30.000Z"
    discountTiers: "1er"
    discountAmount: 3.0
    discount: ""
    number: 1.0
    lowerBound: 1.0
    price: ""
    schedule: "a0F9E000003syg9UAA"
    upperBound: 2.0
    systemModStamp: "2020-01-14T10:26:30.000Z" 
  