#%RAML 1.0 NamedExample
value:
    currency : "EUR"
    lowerBound : null
    maxUpperBound : 0.0
    serviceLevel : "1. Connect"
    priceBookId : "01s1t0000048XiVAAU"
    product : "01t9E000007QMWVQA4"
    regularPrice : 1000.0
    upperBound : null
    discountSchedule : "a0F9E000003syg9UAA"
    status: "Active"