#%RAML 1.0 NamedExample
value: 
  - orderId: "01t1t000001HUk5AAG"
    designationProduct: "Cegid Tax Ultimate 3. Private"
    productId: "A0000044"
  - orderId: "01t1t000001HUkgAAG"
    designationProduct: "Cegid Tax Ultimate 3. Private"
    productId: "A0000044"

  
  