#%RAML 1.0 NamedExample
value: 
  - id: "01t1t000001HUk5AAG"
    referenceNumber: "01t1t000001HUkgAAG"
    productName: "Cegid Tax Ultimate 3. Private"
    solutionRange:  4047
    commercialLaunch: 1966-10-20
    endOfCommercialization: 2066-10-20
    serviceLevels: "3. Private"
    productId: "A0000044"
    priceBookId : "01s1t0000048XiVAAU"
    zuoraEntityId: "056"
  - id: "01t1t000001HUk5AAG" 
    referenceNumber: "01t1t000001HUkgAAG"
    productName: "Cegid Tax Ultimate 3. Private"
    solutionRange: 4047
    commercialLaunch: 1966-10-20
    endOfCommercialization: 2066-10-20
    serviceLevels: "3. Private"
    productId: "A0000044"
    priceBookId : "01s1t0000048XiVAAU"
    zuoraEntityId: "056"

  
  