#%RAML 1.0 NamedExample
value:
  - priceBookId: "a24371bcz2345"
    accountCode : "On Demand" 
    deferredRevenueAccount : "On Demand"
    recognizedRevenueAccount : "On Demand"
    declaratifsRoyalties  : "string"
    regularPrice: 1.0
    currency: "Eur"
    modelCharge : "Tiered" 
    uom: "string"
    name: "string"
    event : "Service Activation"
    chargetype :  "(decode:Recurring>Recurring)"
    discountRate : 100
    productAssetCode : "012349"
    saaSproductionCode : "string"
    productName : "string"
    consommationCode: "string"
    description: "string"
    revenueRules : "Recognize upon invoicing"
    billingPeriod : "Month"
    marketingStatus: ""
  - priceBookId: "a24371bcz2345"
    accountCode : "On Demand" 
    deferredRevenueAccount : "On Demand"
    recognizedRevenueAccount : "On Demand"
    declaratifsRoyalties  : "string"
    regularPrice: 1.0
    currency: "Eur"
    modelCharge : "Tiered" 
    uom: "string"
    name: "string"
    event : "Service Activation"
    chargetype :  "(decode:Recurring>Recurring)"
    discountRate : 100
    productAssetCode : "012349"
    saaSproductionCode : "string"
    productName : "string"
    consommationCode: "string"
    description: "string"
    revenueRules : "Recognize upon invoicing"
    billingPeriod : "Month"
    marketingStatus: ""
