#%RAML 1.0 NamedExample
value:
  discountSchedule: ["a0F9E000003rNN6UAM"]
  referenceNumber: "A0000044"
  productName: "Cegid Tax Ultimate 3. Private"
  solutionRange: "4047"
  commercialLaunch: "1966-10-20"
  endOfCommercialization: "2066-10-20"
  chargeType: ""
  serviceLevels: ["1.connect","2.Private",""]
  productLine: ""
  gamme: ""
  expertise: ""
  productId: "ab123456cg34256"
  priceBookId : "01s1t0000048XiVAAU"
  zuoraEntityId: "056"
  productServiceLevels: ""
  dateSynchronisationZuora: "1966-10-20"     
  isActive: false
  excessPricingMethod:    "" 
  excessUnitPriceCoeff: ""
  family: ""
  functional: "" 
  isLicensesOrSaas: true
  marketingStatus: ""
  maximumQuantity: 3
  metric: "3"
  noRoyalty: true
  consommationCode: ""
  offer: ""
  oneTimePurchases: true
  possibleBillingModes: "" 
  prepaid: true
  pricingModel: "" 
  productCode: ""
  quantityUnitOfMeasure: ""
  recordTypeDeveloperName: ""
  recurringPurchase: ""
  referenceSequence: ""
  regularPrice: 1.0
  currency: "EUR"
  supplierId: ""
  subscriptionLength:  ""
  structureLevel2: ""
  serviceTerm: ""
  schedulable: false
  taxCode: ""
  optional: false
  saasProductionCode: ""

  
  
  