#%RAML 1.0 NamedExample
value:
  startDate : "2020-02-13"
  contractTerm : 36
  accountId : "0019E000016onASQAY"
  priceBookId : "01s1t0000048XiVAAU"
  amendmentPriceBookId : "235dret"
  amendmentRenewalBehavior: "Latest End Date"
  serviceLevel : "I30"
  status : "Activated"