#%RAML 1.0 NamedExample
value:
  - currencyIsoCode: "EUR"
    accountSfId: "0019E000016onASQAY"
    additionalDiscountAmount: null,
    billingFrequency: null
    billingType: null
    bundle: false
    bundledQuantity: null
    bundled: false
    chargeType: "One-Time"
    contractId: "0019E000016onASQAY"
    discountScheduleType: null
    discountSchedule: null
    subscriptionEndDate: "2023-02-12"
    listPrice: 10.0
    markupAmount: null
    markupRate: null
    netPrice: null
    pricingMethod: "List"
    product: "0019E000016onASQAY"
    quantity: 3.0
    regularPrice: null
    renewedDate: "2023-03-13"
    requiredById: null
    requiredByProduct: null
    ratePlanEndDate: null
    ratePlanStartDate: null
    terminatedDate: null
    serviceLevel: null